### ISSUE TITLE
Defect: Major - Image Text block - Trucks: Volvo VNR Electric - Video play button and video link is missing and Font size and alignment of Title and Text is incorrect

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-us#185]
On the Image Text block from the Volvo VNR Electric Truck page - the Video icon and video link on the "Watch next gen VNR Electric..." text is missing as well as the Font size of the text is too large and text is incorrectly aligned to the left instead of centered

**Steps to reproduce:**
01 Go to https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vnr-electric/ and scroll down to the "UNPARALLELED EXPERIENCE With you every step" section of the Image Text block
02. Go to https://www.volvotrucks.us/trucks/vnr-electric/ and scroll down to the "UNPARALLELED EXPERIENCE With you every step" section of the Image Text block
03. Notice that the video play icon and the video link on "[Watch the next-gen VNR Electric Brand Film]" is missing
04. Compare text and notice that the Font Size of Title and Text is larger as well as the alignment is to the left instead of centered

**Expected result**
see the right half of this screenshot

![image (211)](https://user-images.githubusercontent.com/127409602/229481168-ff026584-7d66-4be5-94d9-89e39b7ae06d.png)

**Actual result**
see the left half of this screenshot

![image (211)](https://user-images.githubusercontent.com/127409602/229481222-6b86dd25-0978-4f71-98ee-fc76209eb8a1.png)

**Comment by andreibalanescu** [comment]
This is fixed. Please check and let me know.

**Comment by Andrei-Boiangiu** [comment]
still occurs as described on https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vnr-electric/
 
 
<img width="1903" alt="image" src="https://user-images.githubusercontent.com/127409602/231217259-ebcc8c91-db70-425a-a9a9-ca562b9d683c.png">

**Comment by andreibalanescu** [comment]
The video URL is already embedded , but the icon is this type: class="fa fa-play-circle-o" . So I feel like our Devs should take a look and import it, as I'm not able. Please let me know

**Comment by synox** [comment]
I now fixed the content issue.

**Comment by Joesturbo** [comment]
confirmed closed!

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
