### ISSUE TITLE
Defect: Major: Itorque page has discrepancies in subnavigation

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-volvotrucks-us#220]
**Steps:**
https://www.volvotrucks.us/trucks/powertrain/i-torque/   **does not have sub navigation**
https://www.volvotrucks.us/trucks/emissions/  h**as sub navigation**

however, 

https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/powertrain/i-torque/  **has the sub navigation**
https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/emissions/   **does not have sub navigation**

**Expected vs Actual:**
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/125972657/230380100-e470fb96-9891-450b-b8cb-007314d238f3.png">

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/125972657/230380345-8309ef93-dfb1-4413-a448-39ea0acdf938.png">

**Comment by synox** [comment]
fixed by @Buuhuu

**Comment by girishdigrajkar** [comment]
Hi @synox, @Buuhuu :
Validated and it is partially fixed as https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/powertrain/i-torque/ has no sub navigation as expected 
However,
https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/emissions/  is not yet fixed as no sub navigation is displayed unlike expected hence **reopening** the defect.

![image](https://user-images.githubusercontent.com/125972657/232678393-77609b0b-7a5b-4aff-9609-53784bf962fb.png)

![image](https://user-images.githubusercontent.com/125972657/232678441-fdaf9364-89ca-4dff-9546-08a02ab53ab1.png)

**Comment by synox** [comment]
Sorry for the confusion, fixed now. Please validate.

**Comment by girishdigrajkar** [comment]
Validated now for emissions page and able to see correct results hence, defect could be closed:

![image](https://user-images.githubusercontent.com/125972657/232763923-72a46fee-1567-48e5-8b5e-d36073232e78.png)
