### ISSUE TITLE
Defect: Critical - View Paint Brochure and Compare the Package buttons from all Trucks -> Features pages go to 404 page 

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-us#356]
All View Paint Brochure and where applicable Compare the Package buttons from the Trucks: Features pages take you to dead .pdf links - either 404 page or "An error occured" prompt on the .pdf page is displayed

**Steps to reproduce:**
01. Go to https://www.volvotrucks.us/trucks/vnr/features/
02. Click on View Paint Brochure button
03. Notice the 404 page missing 
04. Click on Compare the packages button 
05. Notice the 404 page missing

06. Repeat the same for all Features pages on Trucks and notice either 404 page or "An error occured" prompt on the .pdf page

**Expected Result**
The correct .pdf file page should be displayed without issues

**Actual result**
404 page missing or an error occurs during the .pdf file page

Note: possibly related to #260

**Comment by Andrei-Boiangiu** [comment]
an error when attempting to open this .pdf file page as well

![image](https://user-images.githubusercontent.com/127409602/233397245-b9aa173f-99ef-43fd-b74a-ecce3dc4e8bb.png)

**Comment by synox** [comment]
Unfortunately, only letters, numbers and dashes are allowed in filenames. Project Franklin will only serve it with a "clean" name.  Basically, all underscores need to be replaced with dashes. 

Trick to find the correct url:

- open https://www.volvotrucks.us/media/vtna/files/en-us/5783-volvo_paint-sample-brochure-for-pdf-english.pdf
- press **edit**
- press **preview**
- it opens https://main--vg-volvotrucks-us--hlxsites.hlx.page/media/vtna/files/en-us/5783-volvo-paint-sample-brochure-for-pdf-english.pdf 


So correct url is https://main--vg-volvotrucks-us--hlxsites.hlx.page/media/vtna/files/en-us/5783-volvo-paint-sample-brochure-for-pdf-english.pdf 

@Andrei-Boiangiu please check if this makes sense and try to update the content.

**Comment by andreibalanescu** [comment]
@Andrei-Boiangiu  this has been fixed.

**Comment by Andrei-Boiangiu** [comment]
> @Andrei-Boiangiu this has been fixed.

Error is still displayed when attempting to open all the "View Paint Brochure" buttons from all the Features subpages of Trucks 

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/127409602/233924972-6046f073-0ade-43bf-8603-b19584108b88.png">

On the **View Paint Brochure** button of the VAH Truck -> Features page there is a 404 page displayed

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/127409602/233925149-617c8c0a-f6ad-4b8a-8d63-963f441ff3a6.png">


 additionally Error on .pdf page is displayed also on Powertrain -> I-Shift Transmission -> I-Shift Product Guide button from comment above
 
 
![image](https://user-images.githubusercontent.com/127409602/233925420-33eece64-6409-4df1-85b1-e394c345d6a7.png)

**Comment by Andrei-Boiangiu** [comment]
confirmed as partially fixed 

except for 
On the View Paint Brochure button of the VAH Truck -> Features page there is a 404 page displayed

![image](https://user-images.githubusercontent.com/127409602/234007561-bd5ce79e-8372-4279-ae1e-d46f2d83624d.png)

**Comment by andreibalanescu** [comment]
@Andrei-Boiangiu  this has been fixed as well. Ticket can be closed.

**Comment by Joesturbo** [comment]
Fixed

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
