### ISSUE TITLE
Defect: Critical - Missing / Broken Links on pages on volvotrucks.us

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-us#382]
On **Trucks -> Powertrain -> I-Shift Transmission page**, the **Find a Dealer** link is missing
https://www.volvotrucks.us/trucks/powertrain/i-shift-transmission/

![image](https://user-images.githubusercontent.com/127409602/233931191-96d83625-7b1f-4f4f-a9ba-52ba0b2f919b.png)

On **Parts and Services -> Parts -> SELECT Part Store page**, the **Dealer Locator for Select Parts Store** button takes you to a 404 page
https://www.volvotrucks.us/parts-and-services/parts/select-part-store/
presumably due to the spaces in the URL 

![image](https://user-images.githubusercontent.com/127409602/233932239-b6d95722-dac9-4b27-b278-dae258c2e6ef.png)

On Our Difference -> Safety -> Active Driver Assist page, the **YouTube Video** link takes you to a 404 page
https://www.volvotrucks.us/our-difference/safety/active-driver-assist/
presumably due to the incorrect YouTube ID in the URL

![image](https://user-images.githubusercontent.com/127409602/233933019-6fbdce59-b9c2-4a84-8880-3c79685d0d43.png)

**Steps to reproduce:**
01. Open the above pages
02. Check for the above metioned buttons / links
03. Notice the missing / 404 pages links

**Expected result:**
Buttons and links should open the correct pages 

 **Actual result:**
 Missing pages / broken links on the above buttons on pages

**Comment by Andrei-Boiangiu** [comment]
The YouTube Video link from On Our Difference -> Safety -> Active Driver Assist page is **fixed**

the other two missing / broken links are still present

**Comment by andreibalanescu** [comment]
I can confirm this is fixed as well, @Andrei-Boiangiu .

**Comment by jonatan-lledo-netcentric** [comment]
I fixed the 1st one, _Find a dealer_ now is working. The second one I'm not sure how to fix it by myself yet

**Comment by andreibalanescu** [comment]
Hi @Andrei-Boiangiu , this ticket is completely fixed and it can be closed. Thank you

**Comment by Andrei-Boiangiu** [comment]
partially fixed 
 
 this link is still broken with 404 at the moment 
 
 
![image](https://user-images.githubusercontent.com/127409602/234288872-841468fe-2d3c-4248-b693-eb098cd19c86.png)

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
